/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITicketNFT } from "./ITicketNFT";
export type { TicketMarketplace } from "./TicketMarketplace";
