/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ticketMarketplaceSol from "./TicketMarketplace.sol";
export type { ticketMarketplaceSol };
export type { TicketNFT } from "./TicketNFT";
